context:
  version: 1.10.3

package:
  name: libsixel
  version: ${{ version }}

source:
  url: https://github.com/libsixel/libsixel/archive/v${{ version }}.tar.gz
  sha256: 028552eb8f2a37c6effda88ee5e8f6d87b5d9601182ddec784a9728865f821e0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - gdk-pixbuf
    - glib
    - libcurl
    - libjpeg-turbo
    - libpng
    - zlib
    - liblzma-devel
  run_exports:
    - ${{ pin_subpackage('libsixel') }}


tests:
  - script:
      - img2sixel -H

about:
  license: MIT
  license_file: LICENSE
  summary: SIXEL encoder/decoder implementation
  homepage: https://github.com/saitoha/sixel
  repository: https://github.com/saitoha/sixel

extra:
  recipe-maintainers:
    - danielnachun
